### PR TITLE
remove prefix from id in transit

### PR DESCRIPTION
**Pull request by paulmr**
to match the same format as the quiz atoms

### CODE REVIEW

**Comment by clloyd** [comment]
:+1:

**Comment by steppenwells** [comment]
My thinking around namespacing the id was that I thought the id may be used as a unique id within capi for atoms. That would work for quizzes which use GUIDs as ids but the viewpoints tool uses a more conventional numbered sequence. As such there could be collisions with other atom providers that also use numbered sequences.

You will also need to update the alternate ids generation implementation for viewpoints in porter to keep the lookup stable, you probably spotted that already.

Happy for this change provided that the id field is not used for anything critical in CAPI.

**Comment by clloyd** [comment]
My understanding from @paulmr is that CAPI is handling the namespacing by type when they insert the atom into ES, so passing viewpoints/123 as an ID resolves to viewpoints/viewpoints/123.

**Comment by steppenwells** [comment]
I'm thinking of the id field as seen in this response:

http://content.code.dev-guardianapis.com/atom/viewpoints/4?api-key=test-internal&user-tier=internal

the id is currently set to viewpoints/4 which was the old transit value

**Pull request merged**
